name: 'Merge PR to Branch'
description: "Handles merging PRs with 'deploy' label to a target branch."
author: 'Deliveroo'
inputs:
  target-branch:
    description: 'The target branch to merge PRs to'
    default: staging
  repo-token:
    description: 'The access token used to access github api'
    default: ${{ github.token }}      
  lock-branch-name:
    description: 'Branch name to use as a semaphore to prevent parallel execution'
    default: lock
  lock-check-interval-ms:
    description: 'Interval to check for the semaphore in milliseconds'
    default: '30000'
runs:
  using: 'docker'
  image: 'Dockerfile'