version: 2

jobs:
  build:
    docker:
      - image: deliveroo/circleci:0.4.1

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash && nvm install node && nvm use

      - run: npm install

      - run: npm run build

      - run: npm test
