version: 2

jobs:
  build:
    docker:
      - image: deliveroo/circleci:4.12.0

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker build -f build.Dockerfile .
