# GLOBAL-ANCHORS - DockerHub Authentication changes applied - PROD-1431 / PROD-1435
global_dockerhub_login: &global_dockerhub_login
  run:
    name: Authenticate with hub.docker.com - DockerHub
    command: docker login -u $GLOBAL_DOCKERHUB_USERNAME -p $GLOBAL_DOCKERHUB_PASSWORD
global_remote_docker: &global_remote_docker
  version: 19.03.13
global_dockerhub_auth: &global_dockerhub_auth
  auth:
    username: $GLOBAL_DOCKERHUB_USERNAME
    password: $GLOBAL_DOCKERHUB_PASSWORD
version: 2

jobs:
  build:
    docker:
      - image: deliveroo/circleci:0.4.1
        <<: *global_dockerhub_auth

    steps:
      - *global_dockerhub_login
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker build -f build.Dockerfile .
