version: 2

jobs:
  build:
    docker:
      - image: deliveroo/circleci:0.4.1

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: npm install

      - run: npm run build

      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
