on:
    pull_request:
      branches:
        - main
      types: [labeled, unlabeled, closed, reopened, synchronize]
    push:
      branches:
        - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: deliveroo/merge-pr-to-branch@v5
